PyPI memary integration
kingjulio8238/memary pull request #29
Opened 2024-05-07 15:28 UTC by kingjulio8238

Requirement for PyPi Integration - setup.py

2024-05-07 16:07 UTC, kingjulio8238 commented
See PR #30 

Additional edits to do before packaging:

1. Update the folder structure to have it as memary/memary folder 
2. Add 'tests' folder but leave empty for now

2024-05-08 14:17 UTC, seyeong-han requested changes
I hope you guys test the codes first and upload them.
Thanks.

2024-05-08 14:17 UTC, seyeong-han commented on pyproject.toml
> +    "llama-index-lms-perplexity==0.1.3",
"llama-index-llms-perplexity==0.1.3",

2024-05-08 14:17 UTC, seyeong-han commented on pyproject.toml
> +    "llama-index-lms-openai==0.1.5",
"llama-index-llms-openai==0.1.5",

2024-05-08 14:17 UTC, seyeong-han commented on pyproject.toml
> +    "llama-index-core==0.1.12",
"llama-index-core==0.10.12",

2024-05-08 14:17 UTC, seyeong-han commented on dist/memary_test-0.1.4-py3-none-any.whl
You should not upload this wheel file to test `pip install`.
You can test it right after building this file locally within a new environment, `pip install dist/memary_test-0.1.4-py3-none-any.whl`
Please run and test `streamlit run app.py` before push the codes.
And you don't have to push this dist directory.

2024-05-09 00:42 UTC, kevinl424 commented
After running `python3 -m build` from the root directory and starting a new virtual environment, running `pip install dist/memary_test-0.1.3-py3-none-any.whl', and changing the `ChatAgent` import to `from memary.agent.chat_agent import ChatAgent` (all the directory stuff would no longer be needed), the streamlit app works.

Following review
- update the two images mentioned in above comment
- push package

2024-05-09 16:00 UTC, kingjulio8238 commented
Note: `pip install dist/memary-0.1.3-py3-none-any.whl` works instead of memary_test

2024-05-09 19:03 UTC, seyeong-han reviewed
I should have told you earlier, but I think it's better to rename `src` as `memary`.
There is no problem with operating codes, but the structure looks redundant.
It depends on your preference. I'm fine with this structure also.

2024-05-09 22:05 UTC, kevinl424 commented
> I should have told you earlier, but I think it's better to rename `src` as `memary`. There is no problem with operating codes, but the structure looks redundant. It depends on your preference. I'm fine with this structure also.

Was thinking under `src` may be better long term just in case we add some other module that goes along with memary, although not sure if that will happen. Prefer to keep it as it is but definitely open to changing it too.

2024-05-09 22:47 UTC, seyeong-han submitted a review, later dismissed
Thanks @kevinl424 @kingjulio8238 .
I tested PyPI build files and all good.
Also, I fixed the README image links to use the local `diagrams` images.
Now, it is good to publish PyPI package after merging this branch.

2024-05-09 22:49 UTC, kevinl424 approved these changes

2024-05-09 23:19 UTC, kevinl424 approved these changes

2024-05-09 23:19 UTC, seyeong-han approved these changes
LGTM

2024-05-09 23:20 UTC, merged