Add FalkorDB  graph database
kingjulio8238/Memary pull request #59
Opened 2024-09-04 14:06 UTC by galshubeli

- Added the FalkorDB graph stores

2024-09-04 17:25 UTC, swilly22 requested changes

2024-09-04 17:25 UTC, swilly22 commented on README.md
> +   FALKORDB_URL="YOUR_FALKORDB_URL"
Provide an example format. e.g. <username:password@host:ip>

2024-09-04 17:25 UTC, swilly22 commented on README.md
> +    - [**FalkorDB**](https://www.falkordb.com/try-free/)
https://app.falkordb.cloud/signin ?

2024-09-04 17:25 UTC, swilly22 commented on src/memary/agent/base_agent.py
> +            self.graph_store = FalkorDBGraphStore(self.falkordb_url,  decode_responses=True)
remove extra space between `self.falkordb_url` and `decode_responses=True`

2024-09-04 17:25 UTC, swilly22 commented on streamlit_app/app.py
> +            rels = [re.search(r':(.*?)\]', str(path.get_edge(i))).group(1) for i in range(path.edge_count())]
Can you please check and share here what's the value of `cypher_query`
this is probably not the way to extract items from the result-set.

2024-09-08 06:21 UTC, galshubeli commented on src/memary/agent/chat_agent.py
> +        vision_model_name="gpt-4-vision-preview",
No good reason, I switched it back.

2024-09-08 06:22 UTC, galshubeli commented on streamlit_app/app.py
> +    if chat_agent.falkordb_url is not None:
Agree

2024-09-08 23:08 UTC, kevinl424 approved these changes

2024-09-08 23:08 UTC, merged