FalkorDB Multi Graph ability
kingjulio8238/Memary pull request #61
Opened 2024-10-10 11:54 UTC by galshubeli

This PR introduces the ability to use multi-graph with the FalkorDB graph database.

2024-10-10 12:04 UTC, swilly22 requested changes

2024-10-10 12:04 UTC, swilly22 commented on src/memary/agent/base_agent.py
> +        user_id='__falkor__',
is that an appropriate user id ?

2024-10-10 12:04 UTC, swilly22 commented on src/memary/agent/base_agent.py
> +            self.graph_store = FalkorDBGraphStore(self.falkordb_url, database=user_id, decode_responses=True)
database is basically the graph key ?

2024-10-10 12:04 UTC, swilly22 commented on streamlit_app/app.py
> +
Add comment explaining this logic

2024-10-10 12:17 UTC, galshubeli commented on src/memary/agent/base_agent.py
> +        user_id='__falkor__',
changed to 'falkor'

2024-10-10 13:01 UTC, galshubeli commented on src/memary/agent/base_agent.py
> +            self.graph_store = FalkorDBGraphStore(self.falkordb_url, database=user_id, decode_responses=True)
yes

2024-10-10 13:07 UTC, swilly22 approved these changes

2024-10-18 01:25 UTC, kingjulio8238 commented on streamlit_app/app.py
> +    submit = st.button("Switch User ID")
"Switch Agent ID" would be more suitable.

2024-10-18 15:10 UTC, galshubeli commented on README.md
> +### Multi-Graph
Please let me know what you think about the step I added.

2024-10-18 17:41 UTC, kevinl424 approved these changes
LGTM!

2024-10-18 21:09 UTC, kingjulio8238 approved these changes
LGTM!

2024-10-18 21:09 UTC, kingjulio8238 approved these changes
All comments resolved

2024-10-18 21:10 UTC, merged

2025-06-07 16:37 UTC, Muaytie666 approved these changes